name: Docker Image CI(github) For [thatyolanda/test:latest]

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"


jobs:
  docker-in-github:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/thatyolandawang/sampleproject:latest

      - name: Artifact
        uses: actions/upload-artifact@main
        with:
          name: windows
          path: ${{ github.workspace }}/artifact/
